# Generated by Django 4.2.11 on 2024-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/img/')),
                ('caption', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
