# Generated by Django 5.0.6 on 2024-05-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblog',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/img/'),
        ),
    ]
