# Generated by Django 4.2.11 on 2024-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
