# Generated by Django 4.2.11 on 2024-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_title_alter_slideritem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
