# Generated by Django 4.2.11 on 2024-05-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Contact',
        ),
    ]
