# Generated by Django 4.2.11 on 2024-05-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_contact_info_info_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=200)),
                ('roles', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='info_contact',
        ),
        migrations.DeleteModel(
            name='Title_contact',
        ),
    ]
