# Generated by Django 4.2.11 on 2024-05-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_personal_info_delete_info_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='adress',
            new_name='address',
        ),
    ]
