# Generated by Django 4.2.11 on 2024-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_about_blog_aboutblog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleabout',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
