# Generated by Django 5.0.6 on 2024-05-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='password',
        ),
    ]
